#!/usr/bin/env python3
"""ClayOS synthetic seed generator.

Emits ONE deterministic SQL transaction to stdout. Pipe it into the database:

    python3 seed/generate.py | docker exec -i clayos_db psql -U clayos -d clayos

Deterministic: fixed RNG seed + uuid5 ids, so re-running yields identical data.
Scope (depth-first): 3 business units + service groups, 6 projects across the
lifecycle, with two fully-detailed active data-center projects:
  * DC-001 Aurora  — deliberately behind & over budget (SPI<1, CPI<1, overbilled)
  * DC-002 Cedar Rapids — healthy (SPI>1, CPI>1)
The script ends by rebuilding the graph (kg_reproject_all) and KPIs.
"""
import datetime as dt
import random
import sys
import uuid

random.seed(42)
NS = uuid.UUID("c1a17005-0000-4000-8000-000000000000")
def uid(*parts): return str(uuid.uuid5(NS, ":".join(str(p) for p in parts)))

TODAY = dt.date(2026, 6, 27)
def days(n): return TODAY + dt.timedelta(days=n)
def months_back(n):  # month-end ~ n months before today
    d = TODAY.replace(day=1)
    for _ in range(n):
        d = (d - dt.timedelta(days=1)).replace(day=1)
    return (d.replace(day=28) + dt.timedelta(days=4)).replace(day=1) - dt.timedelta(days=1)

OUT = []
def w(s=""): OUT.append(s)

def lit(v):
    if v is None: return "NULL"
    if isinstance(v, bool): return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)): return repr(v)
    if isinstance(v, dt.date): return "'" + v.isoformat() + "'"
    return "'" + str(v).replace("'", "''") + "'"

def insert(table, cols, rows):
    if not rows: return
    w(f"INSERT INTO clayos.{table} ({', '.join(cols)}) VALUES")
    body = [",\n".join("(" + ", ".join(lit(r.get(c)) for c in cols) + ")" for r in rows)]
    w(body[0] + ";\n")

# ─────────────────────────────────────────────────────────────────────────────
w("-- ClayOS synthetic seed (generated by seed/generate.py — do not edit by hand)")
w("BEGIN;")
w("SET search_path TO clayos, public, extensions;")
# clean slate (children first via cascade from business_units/projects)
w("TRUNCATE clayos.business_units, clayos.organizations, clayos.persons, clayos.projects,")
w("  clayos.classification_codes RESTART IDENTITY CASCADE;")
w("DELETE FROM clayos.entities; DELETE FROM clayos.edges; DELETE FROM clayos.kpi_history;\n")

# ─── Classification (curated MasterFormat divisions + sections, UniFormat) ────
mf_div = [
    ("01 00 00", "General Requirements"), ("02 00 00", "Existing Conditions"),
    ("03 00 00", "Concrete"), ("04 00 00", "Masonry"), ("05 00 00", "Metals"),
    ("06 00 00", "Wood, Plastics & Composites"), ("07 00 00", "Thermal & Moisture Protection"),
    ("08 00 00", "Openings"), ("09 00 00", "Finishes"), ("21 00 00", "Fire Suppression"),
    ("22 00 00", "Plumbing"), ("23 00 00", "HVAC"), ("26 00 00", "Electrical"),
    ("27 00 00", "Communications"), ("31 00 00", "Earthwork"), ("33 00 00", "Utilities"),
]
mf_sec = {
    "03 00 00": [("03 30 00", "Cast-in-Place Concrete"), ("03 31 00", "Structural Concrete")],
    "05 00 00": [("05 12 00", "Structural Steel Framing"), ("05 50 00", "Metal Fabrications")],
    "07 00 00": [("07 42 00", "Wall Panels"), ("07 50 00", "Membrane Roofing")],
    "08 00 00": [("08 41 00", "Entrances & Storefronts"), ("08 44 00", "Curtain Wall Assemblies")],
    "23 00 00": [("23 60 00", "Central Cooling Equipment"), ("23 70 00", "Air Handling Units")],
    "26 00 00": [("26 20 00", "Low-Voltage Distribution"), ("26 32 00", "Generators"),
                 ("26 33 00", "UPS Systems")],
}
uf = [("A", "Substructure"), ("B", "Shell"), ("C", "Interiors"), ("D", "Services"),
      ("D30", "HVAC"), ("D50", "Electrical"), ("E", "Equipment & Furnishings"),
      ("G", "Sitework")]

cc_rows = []
mf_id = {}
for code, title in mf_div:
    i = uid("mf", code); mf_id[code] = i
    cc_rows.append(dict(id=i, system_id="masterformat", code=code, title=title, parent_id=None))
for div, secs in mf_sec.items():
    for code, title in secs:
        i = uid("mf", code); mf_id[code] = i
        cc_rows.append(dict(id=i, system_id="masterformat", code=code, title=title, parent_id=mf_id[div]))
for code, title in uf:
    i = uid("uf", code)
    parent = uid("uf", code[0]) if len(code) > 1 else None
    cc_rows.append(dict(id=i, system_id="uniformat", code=code, title=title, parent_id=parent))
# parent rows must precede children: divisions/major-groups already first.
insert("classification_codes", ["id", "system_id", "code", "title", "parent_id"], cc_rows)

# ─── Business units (root then children) ─────────────────────────────────────
bu_root = uid("bu", "clayco")
bu = {"clayco": bu_root}
w(f"INSERT INTO clayos.business_units (id,parent_id,slug,name,kind) VALUES "
  f"({lit(bu_root)},NULL,'clayco','Clayco Enterprise','enterprise');\n")
children = [
    ("clayco-compute", "Clayco Compute", "construction"),
    ("clayco-core", "Clayco Construction", "construction"),
    ("crg", "CRG — Clayco Real Estate Group", "real_estate"),
    ("ljc", "Lamar Johnson Collaborative", "architecture"),
    ("shared-services", "Shared Services", "service_group"),
]
bu_rows = []
for slug, name, kind in children:
    i = uid("bu", slug); bu[slug] = i
    bu_rows.append(dict(id=i, parent_id=bu_root, slug=slug, name=name, kind=kind))
insert("business_units", ["id", "parent_id", "slug", "name", "kind"], bu_rows)

# ─── Organizations ───────────────────────────────────────────────────────────
orgs = [
    ("clayco-gc", "Clayco", "gc", None), ("concrete-strategies", "Concrete Strategies", "subcontractor", "Concrete"),
    ("ljc-arch", "Lamar Johnson Collaborative", "architect", None), ("crg-dev", "CRG", "developer", None),
    ("hyperscale", "Hyperscale Cloud Partners", "owner", None), ("midwest-reit", "Midwest Logistics REIT", "owner", None),
    ("biogen", "BioGen Therapeutics", "owner", None), ("stellar", "Stellar Semiconductors", "owner", None),
    ("riverside-dev", "Riverside Development Co", "client", None),
    ("rosendin", "Rosendin Electric", "subcontractor", "Electrical"), ("limbach", "Limbach Mechanical", "subcontractor", "HVAC"),
    ("ideal-steel", "Ideal Steel Erectors", "subcontractor", "Metals"), ("glassview", "Glassview Curtainwall", "subcontractor", "Openings"),
    ("titan-earth", "Titan Earthwork", "subcontractor", "Earthwork"), ("summit-fire", "Summit Fire Protection", "subcontractor", "Fire Suppression"),
    ("apex-plumb", "Apex Plumbing", "subcontractor", "Plumbing"), ("aurora-drywall", "Aurora Drywall & Acoustics", "subcontractor", "Finishes"),
    ("trane", "Trane Technologies", "supplier", "HVAC"), ("schneider", "Schneider Electric", "supplier", "Electrical"),
    ("caterpillar", "Caterpillar Power Systems", "supplier", "Generators"),
    ("aurora-ahj", "City of Aurora Building Dept", "authority", None),
]
org = {}
org_rows = []
for slug, name, typ, trade in orgs:
    i = uid("org", slug); org[slug] = i
    org_rows.append(dict(id=i, name=name, org_type=typ, trade=trade, city="Chicago", state="IL"))
insert("organizations", ["id", "name", "org_type", "trade", "city", "state"], org_rows)

# ─── Persons ─────────────────────────────────────────────────────────────────
FIRST = ["James", "Maria", "David", "Sarah", "Michael", "Jennifer", "Robert", "Linda", "William",
         "Patricia", "Carlos", "Aisha", "Kevin", "Emily", "Daniel", "Grace", "Brian", "Nicole",
         "Andre", "Priya", "Thomas", "Hannah", "Marcus", "Olivia", "Steven", "Rachel"]
LAST = ["Johnson", "Garcia", "Martinez", "Nguyen", "Patel", "Smith", "Brown", "Lee", "Walker",
        "Anderson", "Thomas", "Clark", "Lewis", "Robinson", "Young", "Hall", "Allen", "Wright",
        "Torres", "Kim", "Adams", "Baker", "Rivera", "Campbell", "Murphy", "Cooper"]
ROLE_TITLES = {
    "executive": ["VP Operations", "SVP", "Division President"],
    "project_management": ["Project Executive", "Senior Project Manager", "Project Manager", "Assistant PM"],
    "field": ["Superintendent", "General Superintendent", "Field Engineer", "Safety Foreman"],
    "design": ["Design Director", "Architect", "BIM Manager"],
    "estimating": ["Chief Estimator", "Senior Estimator"],
    "safety": ["Safety Director", "Safety Manager"],
    "recruiting": ["Talent Partner", "Recruiter"],
    "it": ["IT Director", "Systems Engineer"],
    "staffing": ["Resource Manager"],
    "finance": ["Controller", "Project Accountant"],
}
persons = []
pid = []
n = 0
plan = [("clayco-compute", "project_management", 4), ("clayco-compute", "field", 4),
        ("clayco-compute", "design", 2), ("clayco-compute", "executive", 1),
        ("clayco-core", "project_management", 4), ("clayco-core", "field", 4),
        ("clayco-core", "estimating", 2), ("clayco-core", "executive", 1),
        ("crg", "project_management", 3), ("crg", "field", 3),
        ("crg", "executive", 1), ("crg", "finance", 1),
        ("ljc", "design", 4), ("ljc", "project_management", 1),
        ("shared-services", "safety", 3), ("shared-services", "recruiting", 3),
        ("shared-services", "it", 2), ("shared-services", "staffing", 2),
        ("shared-services", "finance", 3)]
for slug, role, cnt in plan:
    for _ in range(cnt):
        fn = FIRST[n % len(FIRST)]; ln = LAST[(n * 7 + 3) % len(LAST)]; n += 1
        i = uid("person", slug, role, n); pid.append((i, slug, role))
        persons.append(dict(id=i, business_unit_id=bu[slug], full_name=f"{fn} {ln}",
                            email=f"{fn.lower()}.{ln.lower()}@clayco.com",
                            title=random.choice(ROLE_TITLES[role]), role_category=role,
                            hire_date=days(-random.randint(200, 3000)),
                            hourly_rate=random.choice([85, 110, 135, 165, 195, 240]), is_active=True))
insert("persons", ["id", "business_unit_id", "full_name", "email", "title", "role_category",
                   "hire_date", "hourly_rate", "is_active"], persons)
def people_in(slug, role=None):
    return [p[0] for p in pid if p[1] == slug and (role is None or p[2] == role)]

# ─── Projects ────────────────────────────────────────────────────────────────
PROJ = [
    dict(key="DC-001", bu="clayco-compute", name="Aurora Hyperscale Data Center", sector="data_center",
         stage="construction", status="active", value=420_000_000, owner="hyperscale", arch="ljc-arch",
         gc="clayco-gc", dev=None, city="Aurora", state="IL", gsf=550000, deep=True,
         planned=0.62, earned=0.52, cpi=0.91, bill_factor=1.08, start=-540, end=210),
    dict(key="DC-002", bu="clayco-compute", name="Cedar Rapids Cloud Campus Ph2", sector="data_center",
         stage="construction", status="active", value=310_000_000, owner="hyperscale", arch="ljc-arch",
         gc="clayco-gc", dev=None, city="Cedar Rapids", state="IA", gsf=410000, deep=True,
         planned=0.50, earned=0.52, cpi=1.06, bill_factor=0.93, start=-360, end=300),
    dict(key="LS-101", bu="clayco-core", name="BioGen Cell Therapy Facility", sector="life_sciences",
         stage="construction", status="active", value=185_000_000, owner="biogen", arch="ljc-arch",
         gc="clayco-gc", dev=None, city="Madison", state="WI", gsf=220000, deep=True,
         planned=0.40, earned=0.41, cpi=0.99, bill_factor=1.0, start=-300, end=360),
    dict(key="IN-220", bu="clayco-core", name="Midwest Logistics Megahub", sector="industrial",
         stage="closeout", status="active", value=95_000_000, owner="midwest-reit", arch="ljc-arch",
         gc="clayco-gc", dev="crg-dev", city="Joliet", state="IL", gsf=1200000, deep=True,
         planned=0.98, earned=0.97, cpi=1.03, bill_factor=0.98, start=-720, end=-30),
    dict(key="SEMI-30", bu="clayco-compute", name="Stellar Fab Expansion", sector="semiconductor",
         stage="precon", status="active", value=640_000_000, owner="stellar", arch="ljc-arch",
         gc="clayco-gc", dev=None, city="Chandler", state="AZ", gsf=900000, deep=True,
         planned=0.05, earned=0.04, cpi=1.0, bill_factor=1.0, start=-90, end=900),
    dict(key="CW-300", bu="ljc", name="Riverside Mixed-Use Tower", sector="commercial",
         stage="design", status="active", value=140_000_000, owner="riverside-dev", arch="ljc-arch",
         gc="clayco-gc", dev="crg-dev", city="Chicago", state="IL", gsf=480000, deep=True,
         planned=0.12, earned=0.11, cpi=1.0, bill_factor=1.0, start=-150, end=720),
    # CRG — Clayco Real Estate Group (development arm). Synthetic instances of CRG's
    # real product brands (The Cubes industrial, Chapter student housing).
    dict(key="CRG-100", bu="crg", name="The Cubes at Stateline", sector="industrial",
         stage="construction", status="active", value=190_000_000, owner="midwest-reit", arch="ljc-arch",
         gc="clayco-gc", dev="crg-dev", city="Hammond", state="IN", gsf=1100000, deep=True,
         planned=0.45, earned=0.43, cpi=0.97, bill_factor=1.02, start=-240, end=240),
    dict(key="CRG-200", bu="crg", name="Chapter at University Commons", sector="multifamily",
         stage="construction", status="active", value=120_000_000, owner="riverside-dev", arch="ljc-arch",
         gc="clayco-gc", dev="crg-dev", city="Champaign", state="IL", gsf=350000, deep=True,
         planned=0.38, earned=0.40, cpi=1.04, bill_factor=0.97, start=-200, end=300),
]
proj_rows = []
P = {}
for p in PROJ:
    i = uid("project", p["key"]); p["id"] = i; P[p["key"]] = p
    proj_rows.append(dict(id=i, business_unit_id=bu[p["bu"]], code=p["key"], name=p["name"],
                         sector=p["sector"], lifecycle_stage=p["stage"], status=p["status"],
                         contract_value=p["value"], owner_org_id=org.get(p["owner"]),
                         gc_org_id=org.get(p["gc"]), architect_org_id=org.get(p["arch"]),
                         developer_org_id=org.get(p["dev"]) if p["dev"] else None,
                         city=p["city"], state=p["state"], gross_sf=p["gsf"],
                         start_date=days(p["start"]), end_date=days(p["end"]),
                         description=f"{p['sector'].replace('_',' ').title()} project — {p['name']}."))
insert("projects", ["id", "business_unit_id", "code", "name", "sector", "lifecycle_stage", "status",
                    "contract_value", "owner_org_id", "gc_org_id", "architect_org_id", "developer_org_id",
                    "city", "state", "gross_sf", "start_date", "end_date", "description"], proj_rows)

# ─── Phases (all projects) ───────────────────────────────────────────────────
PHASES = ["Preconstruction", "Foundations", "Structure", "Enclosure", "MEP Rough-In", "Fit-Out", "Commissioning"]
ph_rows = []
for p in PROJ:
    for seq, name in enumerate(PHASES):
        ph_rows.append(dict(id=uid("phase", p["key"], name), project_id=p["id"], name=name, seq=seq,
                           status="complete" if (p["earned"] > (seq + 1) / len(PHASES)) else
                                  ("active" if p["earned"] > seq / len(PHASES) else "planned")))
insert("phases", ["id", "project_id", "name", "seq", "status"], ph_rows)

# ─── WBS + cost accounts + cost progress + schedule + billing (deep projects) ─
WBS_TEMPLATE = [  # (code, name, masterformat division, cost_type, bac_fraction)
    ("01", "General Conditions", "01 00 00", "overhead", 0.07),
    ("02", "Sitework & Earthwork", "31 00 00", "subcontract", 0.08),
    ("03", "Concrete & Foundations", "03 00 00", "subcontract", 0.14),
    ("04", "Structural Steel", "05 00 00", "subcontract", 0.11),
    ("05", "Building Enclosure", "07 00 00", "subcontract", 0.10),
    ("06", "Curtain Wall & Openings", "08 00 00", "subcontract", 0.06),
    ("07", "Mechanical / Cooling", "23 00 00", "subcontract", 0.16),
    ("08", "Electrical & Power", "26 00 00", "subcontract", 0.15),
    ("09", "Fire Protection", "21 00 00", "subcontract", 0.03),
    ("10", "Interiors & Finishes", "09 00 00", "subcontract", 0.05),
    ("11", "Commissioning", "01 00 00", "labor", 0.05),
]
wbs_rows, ca_rows, cp_rows, act_rows, dep_rows = [], [], [], [], []
payapp_rows, payline_rows, contract_rows = [], [], []
SUB_FOR = {"03 00 00": "concrete-strategies", "31 00 00": "titan-earth", "05 00 00": "ideal-steel",
           "07 00 00": "aurora-drywall", "08 00 00": "glassview", "23 00 00": "limbach",
           "26 00 00": "rosendin", "21 00 00": "summit-fire", "09 00 00": "aurora-drywall"}

def build_project_controls(p, full):
    bac_total = round(p["value"] * 0.86)
    periods = [months_back(k) for k in range(7, -1, -1)] if full else [months_back(0)]
    prev_act = None
    for idx, (code, name, mfdiv, ctype, frac) in enumerate(WBS_TEMPLATE):
        wid = uid("wbs", p["key"], code)
        wbs_rows.append(dict(id=wid, project_id=p["id"], parent_id=None, code=code, name=name,
                            code_id=mf_id.get(mfdiv)))
        bac = round(bac_total * frac)
        caid = uid("ca", p["key"], code)
        ca_rows.append(dict(id=caid, project_id=p["id"], wbs_node_id=wid, masterformat_code_id=mf_id.get(mfdiv),
                           name=name, cost_type=ctype, bac=bac, committed=round(bac * 0.95)))
        for i, per in enumerate(periods):
            frac_t = (i + 1) / len(periods)
            pv = round(bac * p["planned"] * frac_t, 2)
            ev = round(bac * p["earned"] * frac_t, 2)
            ac = round(ev / p["cpi"], 2) if p["cpi"] else ev
            cp_rows.append(dict(id=uid("cp", p["key"], code, i), cost_account_id=caid, period=per,
                               pv=pv, ev=ev, ac=ac))
        if full:
            aid = uid("act", p["key"], code)
            pct = max(0, min(100, round(p["earned"] * 100 + random.randint(-8, 8))))
            act_rows.append(dict(id=aid, project_id=p["id"], wbs_node_id=wid, activity_code=f"A{code}0",
                                name=name, planned_start=days(p["start"] + idx * 40),
                                planned_finish=days(p["start"] + idx * 40 + 60),
                                actual_start=days(p["start"] + idx * 40 + random.randint(0, 10)),
                                actual_finish=days(p["start"] + idx * 40 + 60 + random.randint(-3, 20)) if pct >= 100 else None,
                                pct_complete=pct, is_critical=(idx in (2, 3, 6, 7)),
                                total_float_days=0 if idx in (2, 3, 6, 7) else random.randint(2, 18)))
            if prev_act:
                dep_rows.append(dict(id=uid("dep", p["key"], code), predecessor_id=prev_act,
                                    successor_id=aid, dep_type="FS", lag_days=random.choice([0, 0, 5])))
            prev_act = aid
        # subcontract per trade
        sub = SUB_FOR.get(mfdiv)
        if sub:
            contract_rows.append(dict(id=uid("contract", p["key"], code), project_id=p["id"],
                                     org_id=org[sub], contract_type="subcontract",
                                     masterformat_code_id=mf_id.get(mfdiv), value=round(bac * 0.95),
                                     executed_date=days(p["start"] + 30), status="executed", scope=name))
    # billing: one latest pay app with lines
    earned_rev = p["value"] * p["earned"]
    billings = earned_rev * p["bill_factor"]
    paid = uid("payapp", p["key"], 6)
    payapp_rows.append(dict(id=paid, project_id=p["id"], number=6, period_end=months_back(0),
                           status="approved", submitted_date=months_back(0), approved_date=days(-10)))
    for code, name, mfdiv, ctype, frac in WBS_TEMPLATE:
        sv = round(bac_total * frac)
        wc = round(billings * frac, 2)
        payline_rows.append(dict(id=uid("payline", p["key"], code), pay_app_id=paid,
                                cost_account_id=uid("ca", p["key"], code), description=name,
                                scheduled_value=sv, work_completed_this_period=round(wc * 0.15, 2),
                                work_completed_to_date=wc, materials_stored=0,
                                retainage_pct=5.0, retainage_amount=round(wc * 0.05, 2)))

for p in PROJ:
    build_project_controls(p, full=p["deep"])
insert("wbs_nodes", ["id", "project_id", "parent_id", "code", "name", "code_id"], wbs_rows)
insert("cost_accounts", ["id", "project_id", "wbs_node_id", "masterformat_code_id", "name", "cost_type", "bac", "committed"], ca_rows)
insert("cost_progress", ["id", "cost_account_id", "period", "pv", "ev", "ac"], cp_rows)
insert("schedule_activities", ["id", "project_id", "wbs_node_id", "activity_code", "name", "planned_start",
                               "planned_finish", "actual_start", "actual_finish", "pct_complete", "is_critical", "total_float_days"], act_rows)
insert("schedule_dependencies", ["id", "predecessor_id", "successor_id", "dep_type", "lag_days"], dep_rows)
insert("contracts", ["id", "project_id", "org_id", "contract_type", "masterformat_code_id", "value", "executed_date", "status", "scope"], contract_rows)
insert("pay_apps", ["id", "project_id", "number", "period_end", "status", "submitted_date", "approved_date"], payapp_rows)
insert("pay_app_lines", ["id", "pay_app_id", "cost_account_id", "description", "scheduled_value",
                         "work_completed_this_period", "work_completed_to_date", "materials_stored",
                         "retainage_pct", "retainage_amount"], payline_rows)

# ─── Spaces + building elements + documents (deep projects) ──────────────────
sp_rows, be_rows, doc_rows = [], [], []
def field_activity(p): return p["stage"] in ("construction", "closeout")  # active field work
ELEMENTS_DC = [("CRAH Unit", "IfcAirTerminal", "Trane Technologies", "D30"), ("Switchgear Lineup", "IfcElectricDistributionBoard", "Schneider Electric", "D50"),
            ("Standby Generator", "IfcEngine", "Caterpillar Power Systems", "D50"), ("UPS Module", "IfcElectricFlowStorageDevice", "Schneider Electric", "D50"),
            ("Curtain Wall Panel", "IfcCurtainWall", "Glassview Curtainwall", "B"), ("Structural Steel Beam", "IfcBeam", "Ideal Steel Erectors", "B"),
            ("Concrete Pier", "IfcPile", "Concrete Strategies", "A"), ("Chilled Water Pump", "IfcPump", "Trane Technologies", "D30")]
ELEMENTS_GEN = [("Rooftop Unit", "IfcUnitaryEquipment", "Trane Technologies", "D30"), ("Panelboard", "IfcElectricDistributionBoard", "Schneider Electric", "D50"),
            ("Passenger Elevator", "IfcTransportElement", "Otis", "D"), ("Storefront System", "IfcCurtainWall", "Glassview Curtainwall", "B"),
            ("Structural Steel Beam", "IfcBeam", "Ideal Steel Erectors", "B"), ("Concrete Column", "IfcColumn", "Concrete Strategies", "A"),
            ("VAV Terminal", "IfcAirTerminalBox", "Trane Technologies", "D30"), ("Plumbing Riser", "IfcPipeSegment", "Apex Plumbing", "D")]
SPACE = {"data_center": ("Data Hall", "data_hall"), "industrial": ("Warehouse Bay", "warehouse"),
         "multifamily": ("Residential Floor", "residential"), "life_sciences": ("Cleanroom Suite", "cleanroom"),
         "semiconductor": ("Fab Bay", "fab"), "commercial": ("Office Floor", "office")}
for p in PROJ:
    if not p["deep"]:
        continue
    els = ELEMENTS_DC if p["sector"] == "data_center" else ELEMENTS_GEN
    sp_name, sp_type = SPACE.get(p["sector"], ("Level Area", "general"))
    for lvl in range(1, 3):
        for hall in range(1, 3):
            spid = uid("space", p["key"], lvl, hall)
            sp_rows.append(dict(id=spid, project_id=p["id"], building="Main", level=f"L{lvl}",
                               name=f"{sp_name} {lvl}-{hall}", space_type=sp_type, area_sf=48000))
            for ei, (en, ifc, mfr, ufc) in enumerate(els):
                be_rows.append(dict(id=uid("be", p["key"], lvl, hall, ei), project_id=p["id"], space_id=spid,
                                   uniformat_code_id=uid("uf", ufc) if any(u[0] == ufc for u in uf) else None,
                                   ifc_class=ifc, name=f"{en} {lvl}-{hall}-{ei+1}", manufacturer=mfr,
                                   model=f"M{1000+ei}", status=random.choice(["installed", "procured", "design", "commissioned"])))
    for di in range(12):
        doc_rows.append(dict(id=uid("doc", p["key"], di), project_id=p["id"],
                            doc_type=random.choice(["drawing", "specification", "model", "report"]),
                            number=f"{['A','S','M','E'][di%4]}-{100+di}", revision=f"R{di%3}",
                            title=f"{p['name']} — {'Drawing' if di%4==0 else 'Spec'} {100+di}",
                            discipline=["Architectural", "Structural", "Mechanical", "Electrical"][di % 4],
                            status="issued", issued_date=days(p["start"] + di * 20)))
insert("spaces", ["id", "project_id", "building", "level", "name", "space_type", "area_sf"], sp_rows)
insert("building_elements", ["id", "project_id", "space_id", "uniformat_code_id", "ifc_class", "name", "manufacturer", "model", "status"], be_rows)
insert("documents", ["id", "project_id", "doc_type", "number", "title", "revision", "discipline", "status", "issued_date"], doc_rows)

# ─── RFIs / submittals / daily logs / safety / quality ───────────────────────
RFI_SUBJECTS = ["Curtain wall embed conflict at grid {g}", "Conduit routing clash above {g} corridor",
                "Slab depression dimension at {g}", "Generator pad rebar congestion {g}",
                "Door hardware set mismatch room {g}", "Chilled water pipe penetration at {g}",
                "Switchgear clearance per NEC at {g}", "Roof drain overflow location {g}",
                "Fireproofing thickness at steel {g}", "Louver size discrepancy at {g}"]
rfi_rows, sub_rows, log_rows, safe_rows, qual_rows = [], [], [], [], []
for p in PROJ:
    nrfi = 42 if field_activity(p) else (16 if p["stage"] == "design" else 8)
    be_ids = [r["id"] for r in be_rows if r["project_id"] == p["id"]]
    for k in range(nrfi):
        sub_date = days(p["start"] + 30 + k * 6)
        answered = random.random() < (0.55 if p["key"] == "DC-001" else 0.75)
        ans_date = sub_date + dt.timedelta(days=random.randint(4, 28)) if answered else None
        rfi_rows.append(dict(id=uid("rfi", p["key"], k), project_id=p["id"], number=f"RFI-{k+1:03d}",
                            subject=RFI_SUBJECTS[k % len(RFI_SUBJECTS)].format(g=random.choice(["C-4", "D-7", "B-2", "F-9"])),
                            body="See attached sketch and spec section reference; confirm intended condition.",
                            discipline=random.choice(["Architectural", "Structural", "Mechanical", "Electrical"]),
                            spec_section_code_id=random.choice([mf_id["08 44 00"], mf_id["26 20 00"], mf_id["03 30 00"], mf_id["23 60 00"]]),
                            status="answered" if answered else "open",
                            ball_in_court=random.choice(["Architect", "Engineer", "GC"]),
                            submitted_date=sub_date, due_date=sub_date + dt.timedelta(days=14), answered_date=ans_date,
                            cost_impact=random.choice([None, None, 5000, 24000, 78000]),
                            schedule_impact_days=random.choice([0, 0, 0, 2, 5]),
                            building_element_id=random.choice(be_ids) if be_ids and k % 3 == 0 else None,
                            created_by_person_id=random.choice(people_in(p["bu"]) or [None])))
    if p["deep"]:
        for k in range(20):
            sd = days(p["start"] + 45 + k * 7)
            sub_rows.append(dict(id=uid("sub", p["key"], k), project_id=p["id"], number=f"SUB-{k+1:03d}",
                                title=f"Submittal — {random.choice(['Rebar','Curtain Wall','Switchgear','AHU','Steel'])} {k+1}",
                                spec_section_code_id=random.choice([mf_id["05 12 00"], mf_id["23 70 00"], mf_id["26 33 00"]]),
                                status=random.choice(["approved", "approved_as_noted", "under_review", "submitted", "revise_resubmit"]),
                                submitted_date=sd, returned_date=sd + dt.timedelta(days=random.randint(7, 21)),
                                ball_in_court=random.choice(["Architect", "Engineer"])))
    if field_activity(p):  # daily logs / safety / quality only where there's active field work
        crew = 180 if p["key"] == "DC-001" else 130
        nlogs = 45 if p["stage"] == "construction" else 20
        for k in range(nlogs):
            ld = days(-(nlogs - 1) * 2 + k * 2)  # spread up to today
            log_rows.append(dict(id=uid("log", p["key"], k), project_id=p["id"], log_date=ld,
                                weather=random.choice(["Clear", "Cloudy", "Rain", "Windy"]),
                                temp_high=random.randint(55, 92), temp_low=random.randint(35, 70),
                                manpower_count=crew + random.randint(-40, 40),
                                work_performed=random.choice(["Concrete placement Hall 1", "Steel erection bay 3",
                                    "Curtain wall install east", "MEP rough-in L2", "Switchgear set", "Genyard piping"]),
                                author_person_id=random.choice(people_in(p["bu"], "field") or [None])))
        # safety: DC-001 worse than DC-002
        sev = [("recordable", True, False, "high"), ("recordable", True, False, "medium"),
               ("first_aid", False, False, "low"), ("near_miss", False, False, "low"),
               ("lost_time", True, True, "high")] if p["key"] == "DC-001" else \
              [("near_miss", False, False, "low"), ("observation", False, False, "low"),
               ("first_aid", False, False, "low"), ("recordable", True, False, "medium")]
        for k, (typ, rec, lt, s) in enumerate(sev):
            safe_rows.append(dict(id=uid("safe", p["key"], k), project_id=p["id"], event_date=days(-70 + k * 12),
                                 type=typ, severity=s, recordable=rec, lost_time=lt,
                                 description=f"{typ.replace('_',' ').title()} during {random.choice(['steel erection','MEP install','material handling'])}.",
                                 corrective_action="Toolbox talk + revised JHA.",
                                 person_id=random.choice(people_in(p["bu"], "field") or [None]),
                                 location=random.choice(["Hall 1", "Genyard", "Roof", "Loading dock"])))
        for k in range(15):
            idd = days(-60 + k * 5)
            closed = random.random() < 0.6
            qual_rows.append(dict(id=uid("qual", p["key"], k), project_id=p["id"],
                                 type=random.choice(["inspection", "nonconformance", "punch_item", "test"]),
                                 status="closed" if closed else "open",
                                 building_element_id=random.choice(be_ids) if be_ids and k % 2 == 0 else None,
                                 wbs_node_id=uid("wbs", p["key"], random.choice(["03", "04", "07", "08"])),
                                 description=random.choice(["Weld inspection", "Concrete cylinder break", "Punch: paint touch-up", "Duct leakage test"]),
                                 severity=random.choice(["low", "medium", "high"]),
                                 identified_date=idd, resolved_date=idd + dt.timedelta(days=random.randint(3, 20)) if closed else None))
insert("rfis", ["id", "project_id", "number", "subject", "body", "discipline", "spec_section_code_id", "status",
                "ball_in_court", "submitted_date", "due_date", "answered_date", "cost_impact",
                "schedule_impact_days", "building_element_id", "created_by_person_id"], rfi_rows)
insert("submittals", ["id", "project_id", "number", "title", "spec_section_code_id", "status", "submitted_date", "returned_date", "ball_in_court"], sub_rows)
insert("daily_logs", ["id", "project_id", "log_date", "weather", "temp_high", "temp_low", "manpower_count", "work_performed", "author_person_id"], log_rows)
insert("safety_events", ["id", "project_id", "event_date", "type", "severity", "recordable", "lost_time", "description", "corrective_action", "person_id", "location"], safe_rows)
insert("quality_events", ["id", "project_id", "type", "status", "building_element_id", "wbs_node_id", "description", "severity", "identified_date", "resolved_date"], qual_rows)

# ─── Staffing assignments ────────────────────────────────────────────────────
staff_rows = []
for p in PROJ:
    team = people_in(p["bu"], "project_management") + people_in(p["bu"], "field")
    for person in team[:6]:
        staff_rows.append(dict(id=uid("staff", p["key"], person), person_id=person, project_id=p["id"],
                              role_on_project=random.choice(["PM", "Superintendent", "Field Engineer", "PE"]),
                              allocation_pct=random.choice([50, 100, 100, 25]),
                              start_date=days(p["start"]), end_date=days(p["end"])))
insert("staffing_assignments", ["id", "person_id", "project_id", "role_on_project", "allocation_pct", "start_date", "end_date"], staff_rows)

# ─── Business development: pursuits + estimates ──────────────────────────────
pursuit_rows, est_rows = [], []
PURSUITS = [("clayco-compute", "Phoenix AI Supercluster", "stellar", "data_center", "proposal", 780_000_000, 35),
            ("clayco-compute", "Columbus Hyperscale DC-3", "hyperscale", "data_center", "shortlisted", 350_000_000, 60),
            ("clayco-core", "Indianapolis Gigafactory", "midwest-reit", "industrial", "qualified", 410_000_000, 25),
            ("clayco-core", "Rochester Biomanufacturing", "biogen", "life_sciences", "won", 220_000_000, 100),
            ("clayco-core", "Kansas City Cold Storage", "midwest-reit", "industrial", "lost", 60_000_000, 0),
            ("ljc", "Lakeshore Cultural Center", "riverside-dev", "commercial", "proposal", 95_000_000, 45),
            ("ljc", "University Research Quad", "biogen", "institutional", "identified", 130_000_000, 20),
            ("clayco-compute", "Reno Edge Data Center", "hyperscale", "data_center", "won", 180_000_000, 100)]
for k, (slug, name, client, sector, stage, val, prob) in enumerate(PURSUITS):
    i = uid("pursuit", k)
    pursuit_rows.append(dict(id=i, business_unit_id=bu[slug], name=name, client_org_id=org.get(client),
                            sector=sector, stage=stage, est_value=val, win_probability=prob,
                            go_decision=stage not in ("identified",), identified_date=days(-200 + k * 15),
                            decision_date=days(-30) if stage in ("won", "lost") else None))
    est_rows.append(dict(id=uid("est", k), project_id=None, pursuit_id=i, version=1,
                        estimate_type=random.choice(["conceptual", "schematic", "dd", "gmp"]),
                        total_value=round(val * random.uniform(0.96, 1.04)),
                        status="awarded" if stage == "won" else ("lost" if stage == "lost" else "submitted")))
insert("pursuits", ["id", "business_unit_id", "name", "client_org_id", "sector", "stage", "est_value", "win_probability", "go_decision", "identified_date", "decision_date"], pursuit_rows)
insert("estimates", ["id", "project_id", "pursuit_id", "version", "estimate_type", "total_value", "status"], est_rows)

# ─── Service groups: requisitions + IT assets ────────────────────────────────
req_rows, it_rows = [], []
REQS = [("clayco-compute", "Senior MEP Superintendent", "Field Operations", "interviewing"),
        ("clayco-compute", "Data Center Commissioning Lead", "Commissioning", "open"),
        ("clayco-core", "Project Executive - Life Sciences", "Operations", "offer"),
        ("clayco-core", "Estimator II", "Preconstruction", "filled"),
        ("ljc", "Senior BIM Coordinator", "Design Technology", "open"),
        ("shared-services", "Safety Manager", "EHS", "interviewing"),
        ("shared-services", "Cloud Infrastructure Engineer", "IT", "open"),
        ("clayco-compute", "Quality Control Manager", "Quality", "filled")]
hms = people_in("shared-services", "recruiting")
for k, (slug, title, dept, status) in enumerate(REQS):
    req_rows.append(dict(id=uid("req", k), business_unit_id=bu[slug], title=title, department=dept,
                        status=status, opened_date=days(-120 + k * 10),
                        filled_date=days(-10) if status == "filled" else None,
                        hiring_manager_person_id=hms[k % len(hms)] if hms else None,
                        location=random.choice(["Chicago, IL", "Aurora, IL", "Phoenix, AZ", "Remote"])))
allp = [x[0] for x in pid]
for k in range(30):
    person = allp[k % len(allp)]
    bu_slug = [x[1] for x in pid][k % len(pid)]
    it_rows.append(dict(id=uid("it", k), asset_tag=f"CLY-{4000+k}",
                       asset_type=random.choice(["laptop", "workstation", "tablet", "phone", "license"]),
                       assigned_person_id=person, business_unit_id=bu[bu_slug],
                       status=random.choice(["in_use", "in_use", "available", "repair"]),
                       purchase_date=days(-random.randint(60, 900))))
insert("requisitions", ["id", "business_unit_id", "title", "department", "status", "opened_date", "filled_date", "hiring_manager_person_id", "location"], req_rows)
insert("it_assets", ["id", "asset_tag", "asset_type", "assigned_person_id", "business_unit_id", "status", "purchase_date"], it_rows)

# ─── Backfill KPI history (12 monthly snapshots/project) for trend charts ────
hist_rows = []
for p in PROJ:
    cur_pct, cur_cpi = p["earned"], p["cpi"]
    cur_spi = round(p["earned"] / p["planned"], 3) if p["planned"] else 1.0
    for m in range(1, 13):
        f = (13 - m) / 13.0  # m=1 (recent) ≈ near current, m=12 ≈ early
        vals = {"pct_complete": max(0.0, round(cur_pct * f, 3)),
                "cpi": round(1.0 + (cur_cpi - 1.0) * f + random.uniform(-0.02, 0.02), 3),
                "spi": round(1.0 + (cur_spi - 1.0) * f + random.uniform(-0.02, 0.02), 3)}
        for metric, value in vals.items():
            hist_rows.append(dict(id=uid("hist", p["key"], metric, m), snapshot_date=months_back(m),
                                 business_unit_id=bu[p["bu"]], project_id=p["id"], metric=metric, value=value))
insert("kpi_history", ["id", "snapshot_date", "business_unit_id", "project_id", "metric", "value"], hist_rows)

# ─── Wide portfolio: ~192 light projects (orbit / 200-project stress test) ────
# Uses a SEPARATE RNG (and runs after everything above) so the original 8 deep
# projects — and the eval goldens derived from them — stay byte-identical.
# Light = globe + KPIs + a small cluster (~15-20 entities): condensed cost
# accounts w/ latest EVM period, one pay app, 2 subcontracts, a few RFIs, and
# stage-appropriate field activity. Each project gets a HEAT profile (hot/warm/
# cold) that drives how recent its activity dates are — this is what the 3D
# orbit reads to pull active projects toward the core.
LR = random.Random(4242)
USED_NAMES = {p["name"] for p in PROJ}

CITIES = [("Columbus","OH"),("Phoenix","AZ"),("Nashville","TN"),("Austin","TX"),("Atlanta","GA"),
          ("Dallas","TX"),("Denver","CO"),("Kansas City","MO"),("St. Louis","MO"),("Memphis","TN"),
          ("Louisville","KY"),("Indianapolis","IN"),("Des Moines","IA"),("Omaha","NE"),("Tulsa","OK"),
          ("Reno","NV"),("Boise","ID"),("Salt Lake City","UT"),("Tucson","AZ"),("Albuquerque","NM"),
          ("San Antonio","TX"),("Fort Worth","TX"),("Charlotte","NC"),("Raleigh","NC"),("Richmond","VA"),
          ("Columbia","SC"),("Savannah","GA"),("Jacksonville","FL"),("Tampa","FL"),("Orlando","FL"),
          ("Grand Rapids","MI"),("Detroit","MI"),("Cleveland","OH"),("Cincinnati","OH"),("Pittsburgh","PA"),
          ("Minneapolis","MN"),("Milwaukee","WI"),("Madison","WI"),("Lincoln","NE"),("Green Bay","WI")]
SECTOR_TEMPLATES = {
    "data_center":   ["{c} Hyperscale Data Center", "{c} Cloud Campus", "{c} Edge Data Center"],
    "industrial":    ["{c} Logistics Center", "The Cubes at {c}", "{c} Distribution Hub", "{c} Manufacturing Plant"],
    "life_sciences": ["{c} Bioprocessing Facility", "{c} Lab & cGMP Suite", "{c} Research Tower"],
    "commercial":    ["{c} Corporate Campus", "{c} Gateway Tower", "{c} Innovation Center"],
    "multifamily":   ["Chapter at {c}", "{c} Residences", "{c} Skyline Flats"],
    "institutional": ["{c} Science Quad", "{c} Medical Pavilion", "{c} Student Success Center"],
}
LIGHT_MIX = [  # (bu, sector, code prefix, count, value range $M) — totals 192
    ("clayco-compute", "data_center",   "DC",  38, (60, 480)),
    ("clayco-core",    "industrial",    "IN",  44, (15, 220)),
    ("clayco-core",    "life_sciences", "LS",  22, (40, 260)),
    ("clayco-core",    "commercial",    "CW",  20, (25, 180)),
    ("crg",            "industrial",    "CRG", 20, (40, 240)),
    ("crg",            "multifamily",   "CRG", 18, (30, 160)),
    ("ljc",            "commercial",    "LJC", 16, (10, 120)),
    ("ljc",            "institutional", "LJC", 14, (15, 90)),
]
LIGHT_OWNERS = [("vertex-cloud", "Vertex Cloud Infrastructure", "owner"), ("prologix", "ProLogix Industrial Trust", "owner"),
                ("heartland-health", "Heartland Health Systems", "owner"), ("novacore", "NovaCore Pharma", "owner"),
                ("summit-uni", "Summit State University", "client"), ("blueline", "BlueLine Capital Partners", "owner"),
                ("titanium-reit", "Titanium Industrial REIT", "owner"), ("archline", "Archline Development", "client"),
                ("gridpoint", "GridPoint Energy", "owner"), ("metrolife", "MetroLife Communities", "owner"),
                ("caladan", "Caladan Foods", "owner"), ("keystone-med", "Keystone Medical Group", "owner"),
                ("northgate", "Northgate Ventures", "client"), ("silverbirch", "SilverBirch Living", "owner")]
lo_rows = []
for slug, name, typ in LIGHT_OWNERS:
    i = uid("org", slug); org[slug] = i
    lo_rows.append(dict(id=i, name=name, org_type=typ, trade=None, city="Chicago", state="IL"))
insert("organizations", ["id", "name", "org_type", "trade", "city", "state"], lo_rows)

LIGHT_WBS = [("01", "General Conditions", "01 00 00", "overhead", 0.10),
             ("03", "Structure & Concrete", "03 00 00", "subcontract", 0.30),
             ("07", "Enclosure", "07 00 00", "subcontract", 0.20),
             ("23", "MEP Systems", "23 00 00", "subcontract", 0.40)]
STAGE_PROFILE = {  # stage -> (planned range, start range (days), duration range (days))
    "design":       ((0.05, 0.18), (-220, -30),  (500, 1000)),
    "precon":       ((0.04, 0.22), (-150, -20),  (420, 900)),
    "construction": ((0.20, 0.90), (-540, -120), (240, 700)),
    "closeout":     ((0.94, 1.00), (-780, -540), (480, 620)),
}
SUB_POOL = sorted(set(SUB_FOR.values()))
owner_pool = [s for s, _, t in LIGHT_OWNERS] + ["hyperscale", "midwest-reit", "biogen", "riverside-dev"]

lp_rows, lca_rows, lcp_rows, lpa_rows, lpl_rows, lct_rows = [], [], [], [], [], []
lrfi_rows, llog_rows, lsafe_rows, lhist_rows = [], [], [], []
counters = {}
LIGHT = []
for bu_slug, sector, prefix, count, (vlo, vhi) in LIGHT_MIX:
    for _ in range(count):
        counters[prefix] = counters.get(prefix, 400) + 1
        key = f"{prefix}-{counters[prefix]}"
        city, state = LR.choice(CITIES)
        name = LR.choice(SECTOR_TEMPLATES[sector]).format(c=city)
        # 40 cities × few templates WILL collide — keep names unique (agent lookups are by name)
        if name in USED_NAMES:
            n2 = 2
            while f"{name} Ph{n2}" in USED_NAMES: n2 += 1
            name = f"{name} Ph{n2}"
        USED_NAMES.add(name)
        # LJC (architecture) skews to design; others weighted to construction
        stage = (LR.choices(["design", "precon", "construction", "closeout"], [55, 20, 15, 10])[0]
                 if bu_slug == "ljc" else
                 LR.choices(["design", "precon", "construction", "closeout"], [16, 16, 48, 20])[0])
        (plo, phi), (slo, shi), (dlo, dhi) = STAGE_PROFILE[stage]
        planned = round(LR.uniform(plo, phi), 3)
        earned = round(max(0.0, min(1.0, planned * LR.uniform(0.88, 1.10))), 3)
        cpi = round(LR.uniform(0.88, 1.08), 3)
        value = round(LR.uniform(vlo, vhi)) * 1_000_000
        start = LR.randint(slo, shi); end = start + LR.randint(dlo, dhi)
        # heat: hot projects have recent activity (pulls them toward the orbit core)
        heat = LR.choices(["hot", "warm", "cold"],
                          [55, 30, 15] if stage == "construction" else
                          [25, 40, 35] if stage in ("precon", "design") else [10, 30, 60])[0]
        recency = {"hot": (0, 21), "warm": (21, 90), "cold": (90, 330)}[heat]
        p = dict(key=key, bu=bu_slug, name=name, sector=sector, stage=stage, value=value,
                 planned=planned, earned=earned, cpi=cpi, start=start, end=end,
                 heat=heat, recency=recency, id=uid("project", key))
        LIGHT.append(p)
        lp_rows.append(dict(id=p["id"], business_unit_id=bu[bu_slug], code=key, name=name,
                            sector=sector, lifecycle_stage=stage,
                            status="active", contract_value=value,
                            owner_org_id=org[LR.choice(owner_pool)], gc_org_id=org["clayco-gc"],
                            architect_org_id=org["ljc-arch"],
                            developer_org_id=org["crg-dev"] if bu_slug == "crg" else None,
                            city=city, state=state, gsf=None, start_date=days(start), end_date=days(end),
                            description=f"{sector.replace('_', ' ').title()} project — {name}."))
# projects.gross_sf column is named gross_sf:
for r in lp_rows: r["gross_sf"] = r.pop("gsf")
insert("projects", ["id", "business_unit_id", "code", "name", "sector", "lifecycle_stage", "status",
                    "contract_value", "owner_org_id", "gc_org_id", "architect_org_id", "developer_org_id",
                    "city", "state", "gross_sf", "start_date", "end_date", "description"], lp_rows)

for p in LIGHT:
    bac_total = round(p["value"] * 0.86)
    # condensed cost accounts + latest EVM period (feeds kpi_evm/kpi_wip/backlog)
    for code, cname, mfdiv, ctype, frac in LIGHT_WBS:
        bac = round(bac_total * frac)
        caid = uid("ca", p["key"], code)
        lca_rows.append(dict(id=caid, project_id=p["id"], wbs_node_id=None,
                             masterformat_code_id=mf_id.get(mfdiv), name=cname, cost_type=ctype,
                             bac=bac, committed=round(bac * 0.95)))
        pv = round(bac * p["planned"], 2); ev = round(bac * p["earned"], 2)
        lcp_rows.append(dict(id=uid("cp", p["key"], code, 0), cost_account_id=caid,
                             period=months_back(0), pv=pv, ev=ev,
                             ac=round(ev / p["cpi"], 2) if p["cpi"] else ev))
    # one latest pay app (feeds WIP); bill factor correlates loosely with cpi health
    bill_factor = round(LR.uniform(0.94, 1.08), 3)
    paid = uid("payapp", p["key"], 1)
    lpa_rows.append(dict(id=paid, project_id=p["id"], number=1, period_end=months_back(0),
                         status="approved", submitted_date=months_back(0),
                         approved_date=days(-LR.randint(5, 20))))
    billings = p["value"] * p["earned"] * bill_factor
    for code, cname, mfdiv, ctype, frac in LIGHT_WBS:
        wc = round(billings * frac, 2)
        lpl_rows.append(dict(id=uid("payline", p["key"], code), pay_app_id=paid,
                             cost_account_id=uid("ca", p["key"], code), description=cname,
                             scheduled_value=round(bac_total * frac),
                             work_completed_this_period=round(wc * 0.2, 2), work_completed_to_date=wc,
                             materials_stored=0, retainage_pct=5.0, retainage_amount=round(wc * 0.05, 2)))
    # two subcontracts → cross-portfolio vendor edges (highlight-by-vendor at scale)
    for sub in LR.sample(SUB_POOL, 2):
        lct_rows.append(dict(id=uid("contract", p["key"], sub), project_id=p["id"], org_id=org[sub],
                             contract_type="subcontract", masterformat_code_id=None,
                             value=round(bac_total * LR.uniform(0.08, 0.22)),
                             executed_date=days(p["start"] + 30), status="executed",
                             scope=f"Trade package — {sub.replace('-', ' ')}"))
    # RFIs — dates driven by the heat profile (recent = hot)
    lo, hi = p["recency"]
    nrfi = LR.randint(4, 9) if p["stage"] == "construction" else (LR.randint(2, 5) if p["stage"] == "closeout" else LR.randint(0, 3))
    for k in range(nrfi):
        sub_date = days(-LR.randint(lo, hi + 30))
        answered = LR.random() < 0.7
        lrfi_rows.append(dict(id=uid("rfi", p["key"], k), project_id=p["id"], number=f"RFI-{k+1:03d}",
                              subject=RFI_SUBJECTS[k % len(RFI_SUBJECTS)].format(g=LR.choice(["B-3", "C-5", "E-2", "G-7"])),
                              body="Confirm intended condition per plans/spec.",
                              discipline=LR.choice(["Architectural", "Structural", "Mechanical", "Electrical"]),
                              spec_section_code_id=LR.choice([mf_id["08 44 00"], mf_id["26 20 00"], mf_id["03 30 00"], mf_id["23 60 00"]]),
                              status="answered" if answered else "open",
                              ball_in_court=LR.choice(["Architect", "Engineer", "GC"]),
                              submitted_date=sub_date, due_date=sub_date + dt.timedelta(days=14),
                              answered_date=sub_date + dt.timedelta(days=LR.randint(4, 25)) if answered else None,
                              cost_impact=LR.choice([None, None, None, 12000, 45000]),
                              schedule_impact_days=LR.choice([0, 0, 0, 3]),
                              building_element_id=None, created_by_person_id=None))
    # field activity: daily logs (TRIR hours) + occasional safety events.
    # 20 logs keeps the TRIR denominator realistic — with only a handful of logs,
    # a single recordable produces an absurd 50+ TRIR that reads as fake data.
    if p["stage"] in ("construction", "closeout"):
        crew = LR.randint(60, 210)
        for k in range(20):
            llog_rows.append(dict(id=uid("log", p["key"], k), project_id=p["id"],
                                  log_date=days(-(lo + k * max(2, (hi - lo) // 20))),
                                  weather=LR.choice(["Clear", "Cloudy", "Rain", "Windy"]),
                                  temp_high=LR.randint(55, 92), temp_low=LR.randint(35, 70),
                                  manpower_count=max(10, crew + LR.randint(-15, 15)),
                                  work_performed=LR.choice(["Structure & deck pours", "Enclosure install",
                                                            "MEP rough-in", "Site utilities", "Interior fit-out"]),
                                  author_person_id=None))
        if p["stage"] == "construction" and LR.random() < 0.45:
            for k in range(1):  # at most one event per light project — TRIR stays plausible
                rec = LR.random() < 0.5
                lsafe_rows.append(dict(id=uid("safe", p["key"], k), project_id=p["id"],
                                       event_date=days(-LR.randint(lo, hi + 60)),
                                       type="recordable" if rec else LR.choice(["near_miss", "first_aid", "observation"]),
                                       severity=LR.choice(["low", "medium", "high"]) if rec else "low",
                                       recordable=rec, lost_time=False,
                                       description="Field safety event — see report.",
                                       corrective_action="Toolbox talk + revised JHA.",
                                       person_id=None, location=LR.choice(["Site", "Structure", "Yard"])))
    # 12-month KPI history so trend charts stay meaningful at portfolio scale
    cur_spi = round(p["earned"] / p["planned"], 3) if p["planned"] else 1.0
    for m in range(1, 13):
        f = (13 - m) / 13.0
        for metric, value in {"pct_complete": max(0.0, round(p["earned"] * f, 3)),
                              "cpi": round(1.0 + (p["cpi"] - 1.0) * f + LR.uniform(-0.02, 0.02), 3),
                              "spi": round(1.0 + (cur_spi - 1.0) * f + LR.uniform(-0.02, 0.02), 3)}.items():
            lhist_rows.append(dict(id=uid("hist", p["key"], metric, m), snapshot_date=months_back(m),
                                   business_unit_id=bu[p["bu"]], project_id=p["id"], metric=metric, value=value))

insert("cost_accounts", ["id", "project_id", "wbs_node_id", "masterformat_code_id", "name", "cost_type", "bac", "committed"], lca_rows)
insert("cost_progress", ["id", "cost_account_id", "period", "pv", "ev", "ac"], lcp_rows)
insert("pay_apps", ["id", "project_id", "number", "period_end", "status", "submitted_date", "approved_date"], lpa_rows)
insert("pay_app_lines", ["id", "pay_app_id", "cost_account_id", "description", "scheduled_value",
                         "work_completed_this_period", "work_completed_to_date", "materials_stored",
                         "retainage_pct", "retainage_amount"], lpl_rows)
insert("contracts", ["id", "project_id", "org_id", "contract_type", "masterformat_code_id", "value", "executed_date", "status", "scope"], lct_rows)
insert("rfis", ["id", "project_id", "number", "subject", "body", "discipline", "spec_section_code_id", "status",
                "ball_in_court", "submitted_date", "due_date", "answered_date", "cost_impact",
                "schedule_impact_days", "building_element_id", "created_by_person_id"], lrfi_rows)
insert("daily_logs", ["id", "project_id", "log_date", "weather", "temp_high", "temp_low", "manpower_count", "work_performed", "author_person_id"], llog_rows)
insert("safety_events", ["id", "project_id", "event_date", "type", "severity", "recordable", "lost_time", "description", "corrective_action", "person_id", "location"], lsafe_rows)
insert("kpi_history", ["id", "snapshot_date", "business_unit_id", "project_id", "metric", "value"], lhist_rows)

# ─── Rebuild graph + KPIs ────────────────────────────────────────────────────
w("SELECT clayos.kg_reproject_all();")
w("SELECT clayos.refresh_all_kpis();")
w("SELECT clayos.snapshot_kpis();")
w("COMMIT;")
w("-- done.")

sys.stdout.write("\n".join(OUT) + "\n")
